name: {{ansible_nodename}}
data-dir: /var/lib/etcd
initial-cluster-state: 'new'
initial-cluster-token: 'etcd-cluster-01'
initial-cluster: controller=http://{{ private_ip }}:2380
initial-advertise-peer-urls: http://{{ private_ip }}:2380
advertise-client-urls: http://{{ private_ip }}:2379
listen-peer-urls: http://0.0.0.0:2380
listen-client-urls: http://{{ private_ip }}:2379
