- name: restart openstack-nova-compute
  service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
  with_items:
        - libvirtd.service
        - openstack-nova-compute.service

- name: restart neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent.service enabled=yes state=restarted
  