---
private_ip:  "{{ vars['ansible_'+iface_private]['ipv4']['address'] }}"
external_ip: "{{ vars['ansible_'+iface_external]['ipv4']['address'] }}"
OS_ENVIROMENT:
  OS_USERNAME: admin
  OS_PASSWORD: "{{keystone.admin_passwd}}"
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: Default
  OS_AUTH_URL: http://{{controller.private_fqdn}}:35357/v3
  OS_IDENTITY_API_VERSION: 3