- name: restart mysql
  service:
        name: mariadb
        enabled: yes
        state: restarted

- name: Reload db privileges
  command: 'mysql  -u"{{mysql.root_user}}" -p"{{ mysql.root_passwd }}" -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: restart memcached
  service:
        name: memcached
        enabled: yes
        state: restarted

- name: restart etcd
  service:
        name: etcd
        enabled: yes
        daemon_reload: yes
        state: restarted

- name: Keystone DB sync
  shell: 'keystone-manage db_sync'
  become_user: keystone

- name: Populate the Identity service database
  command: "{{ item }}"
  with_items:
    - 'keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone'
    - 'keystone-manage credential_setup --keystone-user keystone --keystone-group keystone'
    - 'keystone-manage bootstrap --bootstrap-password {{keystone.admin_passwd}} --bootstrap-admin-url http://{{controller.private_fqdn}}:35357/v3/ --bootstrap-internal-url http://{{controller.private_fqdn}}:5000/v3/ --bootstrap-public-url http://{{controller.private_fqdn}}:5000/v3/ --bootstrap-region-id RegionOne'

- name: restart httpd
  service:
        name: httpd.service
        enabled: yes
        state: restarted

- name: Glance DB sync
  shell: 'glance-manage db_sync'
  become_user: glance

- name: restart openstack-glance-api
  service:
        name: openstack-glance-api.service
        enabled: yes
        state: restarted

- name: restart openstack-glance-registry
  service:
        name: openstack-glance-registry.service
        enabled: yes
        state: restarted

- name: Nova-api DB sync
  shell: 'nova-manage api_db sync'
  become_user: nova

- name: register cell0
  shell: 'nova-manage cell_v2 map_cell0'
  become_user: nova

- name: register cell1
  shell: 'nova-manage cell_v2 create_cell --name=cell1 --verbose'
  become_user: nova

- name: Nova DB sync
  shell: 'nova-manage db sync'
  become_user: nova

- name: restart openstack-nova
  service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
  with_items:
        - openstack-nova-api.service
        - openstack-nova-consoleauth.service
        - openstack-nova-scheduler.service
        - openstack-nova-conductor.service
        - openstack-nova-novncproxy.service

- name: restart openstack-nova-api
  service: name=openstack-nova-api.service enabled=yes state=restarted

- name: populate neutron DB
  shell: 'neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head'
  become_user: neutron

- name: restart neutron-server
  service: name=neutron-server.service enabled=yes state=restarted

