---
- name: Dashboard install packages
  yum:
      name: openstack-dashboard
      state: present

- name: Set OpenStack hostname
  lineinfile:
      line: OPENSTACK_HOST = "{{controller.private_fqdn}}"
      path: /etc/openstack-dashboard/local_settings
      regexp: ^OPENSTACK_HOST
  notify: 
      - restart httpd
      - restart memcached

- name: Set Allowed hosts
  lineinfile:
      line: ALLOWED_HOSTS = "{{dashboard.allowed_hosts}}"
      path: /etc/openstack-dashboard/local_settings
      regexp: ^ALLOWED_HOSTS
  notify: 
      - restart httpd
      - restart memcached

- name: Configure memcached
  lineinfile:
      path: /etc/openstack-dashboard/local_settings
      regexp: "('\\s'|\\t)*\\'BACKEND\\'"
      line: "\t'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',"
- name: Configure memcached avi_api_session BACKEND
  lineinfile:
      path: /etc/openstack-dashboard/local_settings
      insertafter: "\t'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',"
      line: "\t'LOCATION': '{{controller.private_fqdn}}:11211',"
  notify: 
      - restart httpd
      - restart memcached

- name: Enable the Identity API version 3
  lineinfile:
      line: OPENSTACK_KEYSTONE_URL = "http://%s:5000/v3" % OPENSTACK_HOST
      path: /etc/openstack-dashboard/local_settings
      regexp: ^OPENSTACK_KEYSTONE_URL
  notify: 
      - restart httpd
      - restart memcached

- name: Enable support for domains
  lineinfile:
      line: OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = "{{dashboard.multidomain}}"
      path: /etc/openstack-dashboard/local_settings
      regexp: OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT
  notify: 
      - restart httpd
      - restart memcached

- name: Configure API versions
  blockinfile:
      path: /etc/openstack-dashboard/local_settings
      insertbefore: "#OPENSTACK_API_VERSIONS"
      block: |
        OPENSTACK_API_VERSIONS = {
            "identity": 3,
            "image": 2,
            "volume": 2,
            "compute": 2,
        }
      marker: "# {mark} API versions"
  notify: 
      - restart httpd
      - restart memcached

- name: Configure Default as the default domain
  lineinfile:
      line: OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = "Default"
      path: /etc/openstack-dashboard/local_settings
      regexp: ^.*OPENSTACK_KEYSTONE_DEFAULT_DOMAIN.?=
  notify: 
      - restart httpd
      - restart memcached

- name: Configure user as the default role
  lineinfile:
      line: OPENSTACK_KEYSTONE_DEFAULT_ROLE = "user"
      path: /etc/openstack-dashboard/local_settings
      regexp: OPENSTACK_KEYSTONE_DEFAULT_ROLE
  notify: 
      - restart httpd
      - restart memcached

- name: Configure the time zone
  lineinfile:
      line: TIME_ZONE = "{{dashboard.timezone}}"
      path: /etc/openstack-dashboard/local_settings
      regexp: TIME_ZONE
  notify: 
      - restart httpd
      - restart memcached
