---
- name: MySQL install
  yum:
     name: mariadb, mariadb-server, python2-PyMySQL, MySQL-python
     state: present

- name: MySQL start
  service:
        name: mariadb
        enabled: yes
        state: started

- name: Define private_ip
  debug: msg={{private_ip}}

- name: Define external_ip
  debug: msg={{external_ip}}

- name: MySQL configuration
  template: src=openstack.cnf dest=/etc/my.cnf.d/openstack.cnf owner=root group=root
  notify: restart mysql 

- include_tasks: mysql_secure.yml
- name: Force all notified handlers
  meta: flush_handlers

- name: RabbitMQ install
  yum:
     name: rabbitmq-server
     state: present

- name: RabbitMQ start
  service:
        name: rabbitmq-server.service
        enabled: yes
        state: started

- name: RabbitMQ add user
  rabbitmq_user:
        user: "{{rabbitmq.user}}"
        password: "{{rabbitmq.passwd}}"
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present

- name: MemCached install
  yum:
     name: memcached, python-memcached
     state: present

- name: MemCached configuration
  template: src=memcached dest=/etc/sysconfig/memcached owner=root group=root
  notify: restart memcached

- name: MemCached start
  service:
        name: memcached.service
        enabled: yes
        state: started

- name: Etcd install
  yum:
     name: etcd
     state: present

- name: Etcd configuration
  template: src=etcd.conf.yml dest=/etc/etcd/etcd.conf.yml owner=etcd group=etcd
  notify: restart etcd

- name: Etcd system unit configure
  lineinfile:
      path: /lib/systemd/system/etcd.service
      regexp: '^ExecStart='
      line: 'ExecStart=/usr/bin/etcd --config-file /etc/etcd/etcd.conf.yml'
      backup: yes
  notify: restart etcd

- name: Etcd start
  service:
        name: etcd.service
        enabled: yes
        state: started

- include_tasks: keystone.yml
- name: Check Keystone services are up and running
  service:
        name: httpd.service
        enabled: yes
        state: started

- include_tasks: glance.yml
- name: Check Image services are up and running
  service:
        name: "{{ item }}"
        enabled: yes
        state: started
  with_items:
        - openstack-glance-api.service
        - openstack-glance-registry.service

#- include_tasks: nova.yml
#- name: Check Compute services are up and running
#  service:
#        name: "{{ item }}"
#        enabled: yes
#        state: started
#  with_items:
#        - openstack-nova-api.service
#        - openstack-nova-consoleauth.service
#        - openstack-nova-scheduler.service
#        - openstack-nova-conductor.service
#        - openstack-nova-novncproxy.service

