---
- name: Neutron DB creation
  mysql_db:
        name: "{{ neutron.db_name }}"
        login_host: "{{ mysql.host }}"
        login_user: "{{ mysql.root_user }}"
        login_password: "{{ mysql.root_passwd }}"
        state: present

- name: Neutron Grant proper access
  mysql_user:
        name: "{{neutron.db_user}}"
        password: "{{neutron.db_passwd}}"
        host: "{{ item }}"
        priv: "{{ neutron.db_name }}.*:ALL"
        login_host: "{{ mysql.host }}"
        login_user: "{{ mysql.root_user }}"
        login_password: "{{ mysql.root_passwd }}"
        state: present
  with_items:
        - "{{ mysql.host }}"
        - "%"
  notify: 
        - Reload db privileges
        - populate neutron DB

- name: Neutron user creation
  os_user:
        name: "{{neutron.user}}"
        password: "{{neutron.passwd}}"
        update_password: on_create
        description: Neutron Service Account
        domain: default
        state: present
        wait: yes
  environment: "{{OS_ENVIROMENT}}"

- name: Add the admin role to the neutron user and service project
  os_user_role:
        role: admin
        user: "{{neutron.user}}"
        project: service
        state: present
        wait: yes
  environment: "{{OS_ENVIROMENT}}"

- name: Neutron service entity creation
  os_keystone_service:
        name: neutron
        service_type: network
        description: OpenStack Networking
        state: present
        wait: yes
  environment: "{{OS_ENVIROMENT}}"

- name: Create the Networking service API endpoints
  os_keystone_endpoint:
        service: neutron
        interface: "{{item}}"
        url: http://{{controller.private_fqdn}}:9696
        region: RegionOne
        state: present
        wait: yes
  environment: "{{OS_ENVIROMENT}}"
  with_items: ['public', 'internal', 'admin']

- name: Neutron install packages
  yum:
      name: openstack-neutron, openstack-neutron-ml2
      state: present

- name: Creation neutron configuration directory
  file: path=/etc/neutron/neutron.conf.d state=directory owner=root group=neutron mode=0750

- name: Copy content neutron configuration
  template: src=neutron.conf.d/{{item}} dest=/etc/neutron/neutron.conf.d
  with_items: [DEFAULT, database, keystone_authtoken, nova, oslo_concurrency]

- name: Neutron configuration
  assemble: backup=yes src=/etc/neutron/neutron.conf.d/ dest=/etc/neutron/neutron.conf owner=root group=neutron mode=0640
  notify: restart neutron-server

- name: Configure ML2 neutron elasticsearch_plugin
  template: src=neutron.conf.d/ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini backup=yes

- name: Create a symlink for ML2 plug-in
  file:
      src: /etc/neutron/plugins/ml2/ml2_conf.ini
      dest: /etc/neutron/plugin.ini
      state: link
  notify: restart neutron-server

- name: Copy neutron configuration for nova
  template: src=nova.conf.d/neutron dest=/etc/nova/nova.conf.d

- name: Nova re-configuration
  assemble: backup=yes src=/etc/nova/nova.conf.d/ dest=/etc/nova/nova.conf owner=root group=nova mode=0640
  notify: restart openstack-nova-api

- name: Force all notified handlers
  meta: flush_handlers

- name: Check Network services are up and running
  service: name=neutron-server.service enabled=yes state=started