---
- name: Neutron install packages
  yum:
      name: openstack-neutron, openstack-neutron-linuxbridge, ebtables
      state: present

- name: Creation neutron configuration directory
  file: path=/etc/neutron/neutron.conf.d state=directory owner=root group=neutron mode=0750

- name: Copy content neutron configuration
  template: src=neutron.conf.d/{{item}} dest=/etc/neutron/neutron.conf.d
  with_items: [DEFAULT, keystone_authtoken, oslo_concurrency]

- name: Neutron configuration
  assemble: backup=yes src=/etc/neutron/neutron.conf.d/ dest=/etc/neutron/neutron.conf owner=root group=neutron mode=0640

- name: Configure Linux bridge agent
  template: src=linuxbridge_agent.ini dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini backup=yes
  notify: restart neutron-linuxbridge-agent

- name: Configure the layer-3 agent
  template: src=l3_agent.ini dest=/etc/neutron/l3_agent.ini backup=yes
  notify: restart neutron-l3-agent

- name: Configure DHCP agent
  template: src=dhcp_agent.ini dest=/etc/neutron/dhcp_agent.ini backup=yes
  notify: restart neutron-dhcp-agent

- name: Configure metadata agent
  template: src=metadata_agent.ini dest=/etc/neutron/metadata_agent.ini backup=yes
  notify: restart neutron-metadata-agent

- name: Force all notified handlers
  meta: flush_handlers

- name: Check Network services are up and running
  service: name={{item}} enabled=yes state=started
  with_items:
        - neutron-linuxbridge-agent.service
        - neutron-l3-agent.service
        - neutron-dhcp-agent.service
        - neutron-metadata-agent.service