- name: Nova install packages
  yum:
      name: openstack-nova-compute
      state: present
  notify: restart openstack-nova-compute

- name: Nova configuration
  template: src=nova.conf dest=/etc/nova/nova.conf owner=root group=nova backup=yes
  notify: restart openstack-nova-compute

- name: Check Compute services are up and running
  service:
        name: "{{ item }}"
        enabled: yes
        state: started
  with_items:
        - libvirtd.service
        - openstack-nova-compute.service
