---
 - hosts: controller
   become: yes
   tasks:
        - name: Install compute service on Controller
          include_role: 
              name: controller
              tasks_from: nova.yml

 - hosts: compute
   tags: add-node
   become: yes
   roles:
        - compute

 - hosts: controller
   tags: add-node
   become: yes
   tasks:
        - name: Discover compute hosts
          shell: 'nova-manage cell_v2 discover_hosts --verbose'
          become_user: nova
